# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Streamism' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Streamism
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'StreamismTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StreamismUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
